spring.application.name=Studentmanage

# MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/studentdb
spring.datasource.username=root
spring.datasource.password=CHAKRI@1812
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring security
spring.security.user.name=Akshith
spring.security.user.password=CHAKRI@1812